services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: worker_cpu:latest
    ports:
      - 8091:8080
    networks:
      - red_ej2



networks:
  red_ej2:
    external: true
