name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: leoduville5/worker_cpu:v5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.YOUR_CLUSTER_NAME }}
          location: ${{ secrets.YOUR_CLUSTER_LOCATION }} # zona o región, ej. us-central1
          project_id: ${{secrets.YOUR_PROJECT_ID}}
      - name: Create Kubernetes Secret for worker_cpu
        run: |
          kubectl create secret generic workercpu-secrets \
            --from-literal=REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --from-literal=RABBITMQ_PASS=${{ secrets.RABBITMQ_PASS }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deploy-coordinador.yaml
          kubectl apply -f k8s/headless-coordinador.yaml
